title: skwiggs
subtitle: iOS Dev
description: >- # this means to ignore newlines until "baseurl:"
  An iOS Dev's personal site

url: "https://skwiggs.dev" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Contact
    url: /contact

# Edit these details

author_logo: profile.jpg
author: Dorian Grolaux
author_shortname: Dorian
author_bio: iOS Dev
author_email: "dorian@skwiggs.dev"
author_location: Amsterdam, NL
author_website_url: "https://skwiggs.dev"

author_work_experiences:
  - company_name: OneFit
    company_logo: about/onefit.png
    company_url: https://google.com
    designation: iOS Developer
    description: Completely overhauled the codebase for their main app
    visibility: true
  - company_name: IBM
    company_logo: about/ibm.jpeg
    company_url: https://ibm.com
    designation: Mobile Developer
    description: At first, I worked on both Android & iOS. Later I specialised in iOS & Swift.
    visibility: true

author_education_details:
  - college_logo: mit.png
    college_name: MIT
    college_url: https://mit.org
    college_degree: Computer Sciences
    description: Bachelor of Technology
    visibility: true

author_project_details:
  - project_thumbnail: about/netswift.png
    project_title: Netswift
    project_description: A type-safe networking library written in Swift
    project_url: https://github.com/mrskwiggs/netswift
    visibility: true

# social links
author_social_links:
  - icon: fa-twitter
    url: https://twitter.com/MrSkwiggs
  - icon: fa-github
    url: https://github.com/MrSkwiggs
  - icon: fa-linkedin-in
    url: https://linkedin.com/in/skwiggs
  - icon: fa-medium
    url: https://medium.com/@skwiggs

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
# wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: dorian@skwiggs.dev

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: false
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
